[package]
name = "typst-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "typst_bindings"

[features]
default = ["embed-fonts"]
embed-fonts = []

[profile.release]
# strip = true
# lto = true

[dependencies]
atty = "0.2"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
codespan-reporting = "0.11"
comemo = "0.3.0"
dirs = "5"
elsa = "1.8"
inferno = "0.11.15"
memmap2 = "0.5"
notify = "5"
once_cell = "1"
open = "4.0.2"
siphasher = "0.3"
tempfile = "3.5.0"
walkdir = "2"
typst = { git = "https://github.com/typst/typst", tag = "v0.5.0" }
typst-library = { git = "https://github.com/typst/typst", tag = "v0.5.0" }
uniffi = { version = "0.24.1", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.24.1", features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
