[package]
name = "typst-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "typst_bindings"

[dependencies]
uniffi = { version = "0.23.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.23.0", features = ["build"] }

[[bin]]

name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"