[package]
name = "typst-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "typst_bindings"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
typst = { git = "https://github.com/typst/typst", tag = "v0.3.0" }
uniffi = { version = "0.23.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.23.0", features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
